chore: fix platformio build (#6)
### Summary

 The build has been broken for sometime now due to an issue including
 components needed for the build. Locally, the error shows up as:

```
CMake Error: Error processing file: /Users/gminnehan/projects/platformio-esp32-espidf/.pio/build/espidf/esp-idf/esp_system/ld/linker_script_generator.cmake
Retrieved `.pio/build/espidf/app_trace/app_trace_util.c.o' from cache
*** [.pio/build/espidf/esp-idf/esp_system/ld/sections.ld.in] Error 1
src/led.c:19:12: fatal error: led_strip.h: No such file or directory

   19 |   #include "led_strip.h"
      |            ^~~~~~~~~~~~~
compilation terminated.
*** [.pio/build/espidf/src/led.c.o] Error 1
```

This PR fixes the build by
 upgrading the PlatformIO core and its dependencies.

A few other notes:
- I was getting some strange errors when building with the
`espressif/toolchain-riscv32-esp` but
`platformio/toolchain-riscv32-esp` worked just fine, so I
switched over 🤷‍♀️ 
- Unfortunately there isn't a version of `tool-ninja` package that
has support for both Linux and MacOS, so specifying the 
wrong version of this package breaks the build 🫠 :

   ```
    Tool Manager: Installing platformio/tool-ninja @ 1.7.1
   UnknownPackageError: Could not find the package with 
   'platformio/tool-ninja @ 1.7.1' requirements for your system 
   'darwin_arm64'
   ```

   I couldn't find an easy way to conditionally include packages in
the `platformio.ini` so I've removed that version pin and added a
comment.

 The original CI logs were [pretty unhelpful](https://github.com/memfault/platformio-esp32-espidf/actions/runs/10960960920/job/30436791360#step:5:182)
 so I've also added the `--verbose` flag to the build command.

 ### Test Plan

CI

---
Resolves: MCU-677